//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.17929.
// 
#pragma warning disable 1591

namespace SimpleLiteDirect3d.marsService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Service1Soap", Namespace="http://tempuri.org/")]
    public partial class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback setbOperationCompleted;
        
        private System.Threading.SendOrPostCallback getbOperationCompleted;
        
        private System.Threading.SendOrPostCallback getb64OperationCompleted;
        
        private System.Threading.SendOrPostCallback setxOperationCompleted;
        
        private System.Threading.SendOrPostCallback getxOperationCompleted;
        
        private System.Threading.SendOrPostCallback getLengthOperationCompleted;
        
        private System.Threading.SendOrPostCallback loginTechnicienOperationCompleted;
        
        private System.Threading.SendOrPostCallback getNomTechnicienOperationCompleted;
        
        private System.Threading.SendOrPostCallback setmatOperationCompleted;
        
        private System.Threading.SendOrPostCallback getMatOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service1() {
            this.Url = global::SimpleLiteDirect3d.Properties.Settings.Default.SimpleLiteDirect3d_marsService_Service1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event setbCompletedEventHandler setbCompleted;
        
        /// <remarks/>
        public event getbCompletedEventHandler getbCompleted;
        
        /// <remarks/>
        public event getb64CompletedEventHandler getb64Completed;
        
        /// <remarks/>
        public event setxCompletedEventHandler setxCompleted;
        
        /// <remarks/>
        public event getxCompletedEventHandler getxCompleted;
        
        /// <remarks/>
        public event getLengthCompletedEventHandler getLengthCompleted;
        
        /// <remarks/>
        public event loginTechnicienCompletedEventHandler loginTechnicienCompleted;
        
        /// <remarks/>
        public event getNomTechnicienCompletedEventHandler getNomTechnicienCompleted;
        
        /// <remarks/>
        public event setmatCompletedEventHandler setmatCompleted;
        
        /// <remarks/>
        public event getMatCompletedEventHandler getMatCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/setb", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void setb(string value, int t) {
            this.Invoke("setb", new object[] {
                        value,
                        t});
        }
        
        /// <remarks/>
        public void setbAsync(string value, int t) {
            this.setbAsync(value, t, null);
        }
        
        /// <remarks/>
        public void setbAsync(string value, int t, object userState) {
            if ((this.setbOperationCompleted == null)) {
                this.setbOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsetbOperationCompleted);
            }
            this.InvokeAsync("setb", new object[] {
                        value,
                        t}, this.setbOperationCompleted, userState);
        }
        
        private void OnsetbOperationCompleted(object arg) {
            if ((this.setbCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.setbCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getb", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] getb() {
            object[] results = this.Invoke("getb", new object[0]);
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void getbAsync() {
            this.getbAsync(null);
        }
        
        /// <remarks/>
        public void getbAsync(object userState) {
            if ((this.getbOperationCompleted == null)) {
                this.getbOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetbOperationCompleted);
            }
            this.InvokeAsync("getb", new object[0], this.getbOperationCompleted, userState);
        }
        
        private void OngetbOperationCompleted(object arg) {
            if ((this.getbCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getbCompleted(this, new getbCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getb64", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getb64() {
            object[] results = this.Invoke("getb64", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getb64Async() {
            this.getb64Async(null);
        }
        
        /// <remarks/>
        public void getb64Async(object userState) {
            if ((this.getb64OperationCompleted == null)) {
                this.getb64OperationCompleted = new System.Threading.SendOrPostCallback(this.Ongetb64OperationCompleted);
            }
            this.InvokeAsync("getb64", new object[0], this.getb64OperationCompleted, userState);
        }
        
        private void Ongetb64OperationCompleted(object arg) {
            if ((this.getb64Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getb64Completed(this, new getb64CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/setx", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void setx(int value) {
            this.Invoke("setx", new object[] {
                        value});
        }
        
        /// <remarks/>
        public void setxAsync(int value) {
            this.setxAsync(value, null);
        }
        
        /// <remarks/>
        public void setxAsync(int value, object userState) {
            if ((this.setxOperationCompleted == null)) {
                this.setxOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsetxOperationCompleted);
            }
            this.InvokeAsync("setx", new object[] {
                        value}, this.setxOperationCompleted, userState);
        }
        
        private void OnsetxOperationCompleted(object arg) {
            if ((this.setxCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.setxCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getx", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int getx() {
            object[] results = this.Invoke("getx", new object[0]);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void getxAsync() {
            this.getxAsync(null);
        }
        
        /// <remarks/>
        public void getxAsync(object userState) {
            if ((this.getxOperationCompleted == null)) {
                this.getxOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetxOperationCompleted);
            }
            this.InvokeAsync("getx", new object[0], this.getxOperationCompleted, userState);
        }
        
        private void OngetxOperationCompleted(object arg) {
            if ((this.getxCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getxCompleted(this, new getxCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getLength", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int getLength() {
            object[] results = this.Invoke("getLength", new object[0]);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void getLengthAsync() {
            this.getLengthAsync(null);
        }
        
        /// <remarks/>
        public void getLengthAsync(object userState) {
            if ((this.getLengthOperationCompleted == null)) {
                this.getLengthOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetLengthOperationCompleted);
            }
            this.InvokeAsync("getLength", new object[0], this.getLengthOperationCompleted, userState);
        }
        
        private void OngetLengthOperationCompleted(object arg) {
            if ((this.getLengthCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getLengthCompleted(this, new getLengthCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/loginTechnicien", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool loginTechnicien(int id, string pass) {
            object[] results = this.Invoke("loginTechnicien", new object[] {
                        id,
                        pass});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void loginTechnicienAsync(int id, string pass) {
            this.loginTechnicienAsync(id, pass, null);
        }
        
        /// <remarks/>
        public void loginTechnicienAsync(int id, string pass, object userState) {
            if ((this.loginTechnicienOperationCompleted == null)) {
                this.loginTechnicienOperationCompleted = new System.Threading.SendOrPostCallback(this.OnloginTechnicienOperationCompleted);
            }
            this.InvokeAsync("loginTechnicien", new object[] {
                        id,
                        pass}, this.loginTechnicienOperationCompleted, userState);
        }
        
        private void OnloginTechnicienOperationCompleted(object arg) {
            if ((this.loginTechnicienCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.loginTechnicienCompleted(this, new loginTechnicienCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getNomTechnicien", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getNomTechnicien() {
            object[] results = this.Invoke("getNomTechnicien", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getNomTechnicienAsync() {
            this.getNomTechnicienAsync(null);
        }
        
        /// <remarks/>
        public void getNomTechnicienAsync(object userState) {
            if ((this.getNomTechnicienOperationCompleted == null)) {
                this.getNomTechnicienOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetNomTechnicienOperationCompleted);
            }
            this.InvokeAsync("getNomTechnicien", new object[0], this.getNomTechnicienOperationCompleted, userState);
        }
        
        private void OngetNomTechnicienOperationCompleted(object arg) {
            if ((this.getNomTechnicienCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getNomTechnicienCompleted(this, new getNomTechnicienCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/setmat", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void setmat(
                    float p0, 
                    float p1, 
                    float p2, 
                    float p3, 
                    float p4, 
                    float p5, 
                    float p6, 
                    float p7, 
                    float p8, 
                    float p9, 
                    float p10, 
                    float p11, 
                    float p12, 
                    float p13, 
                    float p14, 
                    float p15) {
            this.Invoke("setmat", new object[] {
                        p0,
                        p1,
                        p2,
                        p3,
                        p4,
                        p5,
                        p6,
                        p7,
                        p8,
                        p9,
                        p10,
                        p11,
                        p12,
                        p13,
                        p14,
                        p15});
        }
        
        /// <remarks/>
        public void setmatAsync(
                    float p0, 
                    float p1, 
                    float p2, 
                    float p3, 
                    float p4, 
                    float p5, 
                    float p6, 
                    float p7, 
                    float p8, 
                    float p9, 
                    float p10, 
                    float p11, 
                    float p12, 
                    float p13, 
                    float p14, 
                    float p15) {
            this.setmatAsync(p0, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, p12, p13, p14, p15, null);
        }
        
        /// <remarks/>
        public void setmatAsync(
                    float p0, 
                    float p1, 
                    float p2, 
                    float p3, 
                    float p4, 
                    float p5, 
                    float p6, 
                    float p7, 
                    float p8, 
                    float p9, 
                    float p10, 
                    float p11, 
                    float p12, 
                    float p13, 
                    float p14, 
                    float p15, 
                    object userState) {
            if ((this.setmatOperationCompleted == null)) {
                this.setmatOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsetmatOperationCompleted);
            }
            this.InvokeAsync("setmat", new object[] {
                        p0,
                        p1,
                        p2,
                        p3,
                        p4,
                        p5,
                        p6,
                        p7,
                        p8,
                        p9,
                        p10,
                        p11,
                        p12,
                        p13,
                        p14,
                        p15}, this.setmatOperationCompleted, userState);
        }
        
        private void OnsetmatOperationCompleted(object arg) {
            if ((this.setmatCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.setmatCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getMat", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public float[] getMat() {
            object[] results = this.Invoke("getMat", new object[0]);
            return ((float[])(results[0]));
        }
        
        /// <remarks/>
        public void getMatAsync() {
            this.getMatAsync(null);
        }
        
        /// <remarks/>
        public void getMatAsync(object userState) {
            if ((this.getMatOperationCompleted == null)) {
                this.getMatOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetMatOperationCompleted);
            }
            this.InvokeAsync("getMat", new object[0], this.getMatOperationCompleted, userState);
        }
        
        private void OngetMatOperationCompleted(object arg) {
            if ((this.getMatCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getMatCompleted(this, new getMatCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void setbCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void getbCompletedEventHandler(object sender, getbCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getbCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getbCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void getb64CompletedEventHandler(object sender, getb64CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getb64CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getb64CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void setxCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void getxCompletedEventHandler(object sender, getxCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getxCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getxCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void getLengthCompletedEventHandler(object sender, getLengthCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getLengthCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getLengthCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void loginTechnicienCompletedEventHandler(object sender, loginTechnicienCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class loginTechnicienCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal loginTechnicienCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void getNomTechnicienCompletedEventHandler(object sender, getNomTechnicienCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getNomTechnicienCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getNomTechnicienCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void setmatCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void getMatCompletedEventHandler(object sender, getMatCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getMatCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getMatCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public float[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((float[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591